### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by minrk** [americandatascience/jh-client#1]
Cool project! I wanted to try it out and noticed that there is no LICENSE file. I see [in the metadata](https://github.com/americandatascience/jh-client/blob/44cf657a9602daca18da3be0aa23a80b0014b42c/pyproject.toml#L6) that it's BSD-3, but the license file itself is missing.

**Comment by aychang95** [comment]
Ah thanks for reminding me! It's BSD-3 and I just added it to this and the nbserv-client
